version: '3'

services:

  nginx:
    image: nginx:1.15.9-alpine
    networks:
      - poc_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: proxy
    restart: always
    ports:
      - 80:80

  back-end:
    build: ./back-end
    networks:
      - poc_proxy
    volumes:
      - ./back-end/app:/usr/local/node/app
    container_name: backend
    restart: always
    depends_on:
      - nginx
    ports:
      - 8881:3000

networks:
  poc_proxy: